### ISSUE TITLE
Searching by category is broken.

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/EDGAR#23]
Currently, the category argument is passed to the API as a URL parameter derived from the [`TEXT_SEARCH_FILING_CATEGORIES_MAPPING`](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/constants.py#L3):

`&category=form-cat3`

which doesn't appear to affect the search results.

Instead the [`TEXT_SEARCH_CATEGORY_FORM_GROUPINGS`](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/constants.py#L1394C1-L1394C37) should be used to set the `forms` URL parameter instead.

`&forms=10-12B,10-12G,18-12B,20FR12B, ...`

Additionally, perhaps the users should be able to set the forms directly - either providing a Category from the mapping, or a list of forms of interest.

**Comment by NauelSerraino** [comment]
Hi, can I try to solve this? Thanks :)

**Comment by GalenReich** [comment]
Hi @NauelSerraino, that would be great, thank you! 🙌 I'll assign this issue to you. Hopefully there isn't any hidden complexity, but feel free to share any issues you have, and do tag me in your PR when it's ready. I can also unassign you if you need to stop working on it for any reason.

**Comment by NauelSerraino** [comment]
Hi there @GalenReich I've updated a beta version that simply add the parameter [TEXT_SEARCH_CATEGORY_FORM_GROUPINGS](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/constants.py#L1394C1-L1394C37), which effectively changes the output of the `csv`. I hope to be ready for the final PR by the end of this week.

I noticed that both with the old and new version the output contains a ton of duplicates, is this behavior expected? It might be a further issue to open and fix.

Reference:
```python
import pandas as pd

CSV_1 = r"C:\EDGAR\test\edgar_test_results_20240515_000000_all_except_section_16.csv"
df_1 = pd.read_csv(CSV_1)

cols = df_1.columns.to_list()
df_1_no_dup = df_1.drop_duplicates(subset=cols)

print(f"Shape of df_1: {df_1.shape}")
print(f"Shape of df_1_no_dup: {df_1_no_dup.shape}")

>>> Shape of df_1: (2000, 16)
>>> Shape of df_1_no_dup: (100, 16)
```

**Comment by NauelSerraino** [comment]
Hi @GalenReich I'm working on the issue, since the [TEXT_SEARCH_FILING_CATEGORIES_MAPPING](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/constants.py#L3) does not affect the search results, is it ok to simple substitute the [TEXT_SEARCH_CATEGORY_FORM_GROUPINGS](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/constants.py#L1394C1-L1394C37) inside the [filing_type](https://github.com/bellingcat/EDGAR/blob/3c2890a4863b2f734a462fbbbbcae6fd51358648/edgar_tool/cli.py#L19)? 

Or is more reasonable to create a new argument within the text search?

**Comment by GalenReich** [comment]
I couldn't see any effects of the `category` parameter, and it sounds like you haven't either, which gives me confidence that it isn't doing anything, so I'd be happy with its removal!
