### ISSUE TITLE
Replace Selenium

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/EDGAR#8]
I'm not sure that Selenium is necessary and adds some friction to the tool.

Would GET requests to the endpoint work? There will stll need to be some HTML parsing of the results as I don't believe there is a nicely structured API for this.

**Comment by GeorgeDyer** [comment]
I had trouble using GET requests for iterating through the results pages, but off the top of my head I cannot articulate the reason why. I will look into this during the refactor!

**Comment by GalenReich** [comment]
Thanks for that George! There's a developer from the community who is going to be taking a look at some of these issues I'm creating (don't worry I'm not creating a load of new tasks for you!). So any information you can provide on what you have already tried would be amazing 🙌

**Comment by wenlambdar** [comment]
For the sake of documenting it here: I've tried using `requests-html` library since I was also having issues displaying the results table using standard `requests` library, which seems to require a proper JavaScript client. 

However there was an [issue with headers' settings]( https://github.com/psf/requests-html/issues/526) which made me fall back to Selenium. Anyway, requests-html is using Chromium under the hood, just as Selenium does (for Chromium-based drivers obviously).
